name: Setup
description: Setup the environment for the runner

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        experimental: true
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
