package invalidaction

var knownTopLevelKeys = map[string]bool{
	"name": true, "description": true, "author": true,
	"inputs": true, "outputs": true, "runs": true, "branding": true,
}

var knownJSRunsKeys = map[string]bool{
	"using": true, "main": true, "pre": true, "pre-if": true, "post": true, "post-if": true,
}

var knownCompositeRunsKeys = map[string]bool{
	"using": true, "steps": true,
}

var knownDockerRunsKeys = map[string]bool{
	"using": true, "image": true, "env": true, "entrypoint": true,
	"pre-entrypoint": true, "pre-if": true, "post-entrypoint": true, "post-if": true, "args": true,
}

var knownUsingValues = map[string]bool{
	"composite": true, "node12": true, "node16": true, "node20": true, "node24": true, "docker": true,
}

var jsUsingValues = map[string]bool{
	"node12": true, "node16": true, "node20": true, "node24": true,
}

var knownCompositeStepKeys = map[string]bool{
	"run": true, "shell": true, "uses": true, "with": true, "name": true,
	"id": true, "if": true, "env": true, "continue-on-error": true, "working-directory": true,
}

var knownInputKeys = map[string]bool{
	"description": true, "required": true, "default": true, "deprecationMessage": true,
}

var knownOutputKeys = map[string]bool{
	"description": true,
}

var knownCompositeOutputKeys = map[string]bool{
	"description": true, "value": true,
}

var knownBrandingKeys = map[string]bool{
	"color": true, "icon": true,
}

var knownBrandingColors = map[string]bool{
	"white": true, "black": true, "yellow": true, "blue": true, "green": true,
	"orange": true, "red": true, "purple": true, "gray-dark": true,
}

var knownBrandingIcons = map[string]bool{
	"activity":           true,
	"airplay":            true,
	"alert-circle":       true,
	"alert-octagon":      true,
	"alert-triangle":     true,
	"align-center":       true,
	"align-justify":      true,
	"align-left":         true,
	"align-right":        true,
	"anchor":             true,
	"aperture":           true,
	"archive":            true,
	"arrow-down-circle":  true,
	"arrow-down-left":    true,
	"arrow-down-right":   true,
	"arrow-down":         true,
	"arrow-left-circle":  true,
	"arrow-left":         true,
	"arrow-right-circle": true,
	"arrow-right":        true,
	"arrow-up-circle":    true,
	"arrow-up-left":      true,
	"arrow-up-right":     true,
	"arrow-up":           true,
	"at-sign":            true,
	"award":              true,
	"bar-chart-2":        true,
	"bar-chart":          true,
	"battery-charging":   true,
	"battery":            true,
	"bell-off":           true,
	"bell":               true,
	"bluetooth":          true,
	"bold":               true,
	"book-open":          true,
	"book":               true,
	"bookmark":           true,
	"box":                true,
	"briefcase":          true,
	"calendar":           true,
	"camera-off":         true,
	"camera":             true,
	"cast":               true,
	"check-circle":       true,
	"check-square":       true,
	"check":              true,
	"chevron-down":       true,
	"chevron-left":       true,
	"chevron-right":      true,
	"chevron-up":         true,
	"chevrons-down":      true,
	"chevrons-left":      true,
	"chevrons-right":     true,
	"chevrons-up":        true,
	"circle":             true,
	"clipboard":          true,
	"clock":              true,
	"cloud-drizzle":      true,
	"cloud-lightning":    true,
	"cloud-off":          true,
	"cloud-rain":         true,
	"cloud-snow":         true,
	"cloud":              true,
	"code":               true,
	"command":            true,
	"compass":            true,
	"copy":               true,
	"corner-down-left":   true,
	"corner-down-right":  true,
	"corner-left-down":   true,
	"corner-left-up":     true,
	"corner-right-down":  true,
	"corner-right-up":    true,
	"corner-up-left":     true,
	"corner-up-right":    true,
	"cpu":                true,
	"credit-card":        true,
	"crop":               true,
	"crosshair":          true,
	"database":           true,
	"delete":             true,
	"disc":               true,
	"dollar-sign":        true,
	"download-cloud":     true,
	"download":           true,
	"droplet":            true,
	"edit-2":             true,
	"edit-3":             true,
	"edit":               true,
	"external-link":      true,
	"eye-off":            true,
	"eye":                true,
	"fast-forward":       true,
	"feather":            true,
	"file-minus":         true,
	"file-plus":          true,
	"file-text":          true,
	"file":               true,
	"film":               true,
	"filter":             true,
	"flag":               true,
	"folder-minus":       true,
	"folder-plus":        true,
	"folder":             true,
	"gift":               true,
	"git-branch":         true,
	"git-commit":         true,
	"git-merge":          true,
	"git-pull-request":   true,
	"globe":              true,
	"grid":               true,
	"hard-drive":         true,
	"hash":               true,
	"headphones":         true,
	"heart":              true,
	"help-circle":        true,
	"home":               true,
	"image":              true,
	"inbox":              true,
	"info":               true,
	"italic":             true,
	"layers":             true,
	"layout":             true,
	"life-buoy":          true,
	"link-2":             true,
	"link":               true,
	"list":               true,
	"loader":             true,
	"lock":               true,
	"log-in":             true,
	"log-out":            true,
	"mail":               true,
	"map-pin":            true,
	"map":                true,
	"maximize-2":         true,
	"maximize":           true,
	"menu":               true,
	"message-circle":     true,
	"message-square":     true,
	"mic-off":            true,
	"mic":                true,
	"minimize-2":         true,
	"minimize":           true,
	"minus-circle":       true,
	"minus-square":       true,
	"minus":              true,
	"monitor":            true,
	"moon":               true,
	"more-horizontal":    true,
	"more-vertical":      true,
	"move":               true,
	"music":              true,
	"navigation-2":       true,
	"navigation":         true,
	"octagon":            true,
	"package":            true,
	"paperclip":          true,
	"pause-circle":       true,
	"pause":              true,
	"percent":            true,
	"phone-call":         true,
	"phone-forwarded":    true,
	"phone-incoming":     true,
	"phone-missed":       true,
	"phone-off":          true,
	"phone-outgoing":     true,
	"phone":              true,
	"pie-chart":          true,
	"play-circle":        true,
	"play":               true,
	"plus-circle":        true,
	"plus-square":        true,
	"plus":               true,
	"pocket":             true,
	"power":              true,
	"printer":            true,
	"radio":              true,
	"refresh-ccw":        true,
	"refresh-cw":         true,
	"repeat":             true,
	"rewind":             true,
	"rotate-ccw":         true,
	"rotate-cw":          true,
	"rss":                true,
	"save":               true,
	"scissors":           true,
	"search":             true,
	"send":               true,
	"server":             true,
	"settings":           true,
	"share-2":            true,
	"share":              true,
	"shield-off":         true,
	"shield":             true,
	"shopping-bag":       true,
	"shopping-cart":      true,
	"shuffle":            true,
	"sidebar":            true,
	"skip-back":          true,
	"skip-forward":       true,
	"slash":              true,
	"sliders":            true,
	"smartphone":         true,
	"speaker":            true,
	"square":             true,
	"star":               true,
	"stop-circle":        true,
	"sun":                true,
	"sunrise":            true,
	"sunset":             true,
	"table":              true,
	"tablet":             true,
	"tag":                true,
	"target":             true,
	"terminal":           true,
	"thermometer":        true,
	"thumbs-down":        true,
	"thumbs-up":          true,
	"toggle-left":        true,
	"toggle-right":       true,
	"trash-2":            true,
	"trash":              true,
	"trending-down":      true,
	"trending-up":        true,
	"triangle":           true,
	"truck":              true,
	"tv":                 true,
	"type":               true,
	"umbrella":           true,
	"underline":          true,
	"unlock":             true,
	"upload-cloud":       true,
	"upload":             true,
	"user-check":         true,
	"user-minus":         true,
	"user-plus":          true,
	"user-x":             true,
	"user":               true,
	"users":              true,
	"video-off":          true,
	"video":              true,
	"voicemail":          true,
	"volume-1":           true,
	"volume-2":           true,
	"volume-x":           true,
	"volume":             true,
	"watch":              true,
	"wifi-off":           true,
	"wifi":               true,
	"wind":               true,
	"x-circle":           true,
	"x-square":           true,
	"x":                  true,
	"zap-off":            true,
	"zap":                true,
	"zoom-in":            true,
	"zoom-out":           true,
}
